### ISSUE TITLE
first steps -> 3. What's in a Vector -> What's the length - newbie question

### ISSUE THREAD

**Issue by ktprezes** [Dyalog/APLCourse#16]
```APL
Hello
in the file:
https://github.com/Dyalog/APLCourse/blob/master/docs/First-steps.md
in the section "3. What's in a Vector", in the question "3. What's the length of an ⎕AVU vector"
why do not you use the  ⍴(⎕AVU)  expression to calculate the length of that vector?
is not it shorter and clearer than the expressions provided as the sample answers?
consequently, the mean would be calculated as  (+/⎕AVU)÷⍴(⎕AVU)

best regards
T.Kurpiel

**Comment by rikedyp** [comment]
I'm sorry for taking so long to respond to your issues. Thanks for taking a look at the course and providing feedback!

That's a totally fair question - one of the approaches of this course material was to try and emphasise what "array-oriented" solutions to problems would be as early as possible, and one attempt at doing that was to only let students use what had been explicitly introduced so far to try and solve problems, but keeping the problems simple enough that they know what the result should be, and figuring out how to do it was the task (in contrast to the first page where once you've figured out the sugar cube patterns, coding the solution is trivial).

The feedback I've received suggests that these problems would be phrased better as "broken keyboard problems" for more beginner-intermediate learners.

**Comment by rikedyp** [comment]
this has been addressed in the latest revision - alternative element count (tally) is in Broken Keyboard Problems
